# Generated by Django 5.1 on 2024-08-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DurationField(blank=True),
        ),
    ]
