# Generated by Django 5.1 on 2024-08-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_alter_todo_finished_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateField(blank=True),
        ),
    ]
